/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedCoordinatorRouteImport } from './routes/_authenticated/coordinator'
import { Route as AuthenticatedFamiliesRouteImport } from './routes/_authenticated/families'
import { Route as AuthenticatedSourceRouteImport } from './routes/_authenticated/source'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordinatorRoute =
  AuthenticatedCoordinatorRouteImport.update({
    id: '/coordinator',
    path: '/coordinator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamiliesRoute = AuthenticatedFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourceRoute = AuthenticatedSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/coordinator': typeof AuthenticatedCoordinatorRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/source': typeof AuthenticatedSourceRoute
  '/worker': typeof AuthenticatedWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/coordinator': typeof AuthenticatedCoordinatorRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/source': typeof AuthenticatedSourceRoute
  '/worker': typeof AuthenticatedWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/coordinator': typeof AuthenticatedCoordinatorRoute
  '/_authenticated/families': typeof AuthenticatedFamiliesRoute
  '/_authenticated/source': typeof AuthenticatedSourceRoute
  '/_authenticated/worker': typeof AuthenticatedWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending'
    | '/accounts'
    | '/coordinator'
    | '/families'
    | '/source'
    | '/worker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/accounts'
    | '/coordinator'
    | '/families'
    | '/source'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pending'
    | '/_authenticated/accounts'
    | '/_authenticated/coordinator'
    | '/_authenticated/families'
    | '/_authenticated/source'
    | '/_authenticated/worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator': {
      id: '/_authenticated/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof AuthenticatedCoordinatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/families': {
      id: '/_authenticated/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof AuthenticatedFamiliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/source': {
      id: '/_authenticated/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof AuthenticatedSourceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedCoordinatorRoute: typeof AuthenticatedCoordinatorRoute
  AuthenticatedFamiliesRoute: typeof AuthenticatedFamiliesRoute
  AuthenticatedSourceRoute: typeof AuthenticatedSourceRoute
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedCoordinatorRoute: AuthenticatedCoordinatorRoute,
  AuthenticatedFamiliesRoute: AuthenticatedFamiliesRoute,
  AuthenticatedSourceRoute: AuthenticatedSourceRoute,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
